server.port=8070

spring.datasource.url=jdbc:postgresql://localhost:5432/order
spring.datasource.username=faheem
spring.datasource.password=faheem123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer= org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=orderConfirmation:com.faheem.ecommerce.kafka.OrderConfirmation


application.config.customer-url=http://localhost:8222/api/v1/customers
application.config.product-url=http://localhost:8222/api/v1/products
application.config.payment-url=http://localhost:8222/api/v1/payments

logging.level.org.springframework.cloud=DEBUG

